name: Flutter Web

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Web
    env:
      BITBUCKET_USERNAME: ${{ secrets.BITBUCKET_USERNAME }}
      BITBUCKET_PASSWORD: ${{ secrets.BITBUCKET_PASSWORD }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.7'

      - name: Deploy to Bitbucket

        run: |
          git clone https://$BITBUCKET_USERNAME:$BITBUCKET_PASSWORD@bitbucket.org/sumerlabs/sumer-app-design-system.git

      - run: flutter pub get

      - uses: bluefireteam/flutter-gh-pages@v7
        with:
          baseHref: /

